### ISSUE TITLE
Consolidate community documentation to this repo

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/community#87]
We have many repos with different versions of welcome, contributing, and style guides.  I would like for all of the these pages to be moved this following hierarchy to follow suit with CNCF/Kubernetes ....

```
kubevirt/community:
  - contributors:
      - README.md: https://github.com/kubernetes/community/tree/master/contributors/devel/README.md
      - CONTRIBUTING.md
      - example_subproject: https://github.com/kubernetes/community/tree/master/contributors/devel/sig-api-machinery
          RELEASES.md
          STLYE_GUIDE.md
          etc       
      - guides: https://github.com/kubernetes/community/tree/master/contributors/guide
        - automation.md: https://github.com/kubernetes/community/blob/master/contributors/devel/automation.md
        - first_contribution.md: https://github.com/kubernetes/community/blob/master/contributors/guide/first-contribution.md
        - owners.md: https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md
```

The repo page gets a stub page (example: [kubernetes/apimachinary/CONTRIBUTING.md](https://github.com/kubernetes/apimachinery/blob/master/CONTRIBUTING.md) )

A secondary object is to sync these pages to the user-guide appendix
